### ISSUE TITLE
What features does ld-reactor include?

### ISSUE THREAD

**Issue by killercup** [ali1k/ld-r#1]
Hi,

I'm about to begin a project using data from a SPARQL server and possibly React myself and found ld-reactor. What is the goal of this project? Editing generic linked data? What features are currently supported?

Sadly, I couldn't get ld-reactor to work with my local instance of Jena/Fuseki 2 (I get a bunch of parse errors, if you're interested in this, I can easily give you more information), so I can't really test this myself.

**Comment by ali1k** [comment]
Hi @killercup 
LD-Reactor is still in the development phase. it is an ecosystem for reusable Linked Data component to view/edit/browse RDF data. I will soon publish a comprehensive documentation about the features. At the moment, it works only with Virtuoso triple store, however, it should not be difficult to change the triple store.

**Comment by killercup** [comment]
Thanks for the quick answer, @ali1k!

Currently, I'm mostly interested in browsing data with known entries and displaying them (with special formatting for some of the known entity types). Is this something you are doing as well?

Interesting, but sadly not surprising, that Virtuoso and Fuseki seem to have different understanding of what is a valid SPARQL query…

**Comment by ali1k** [comment]
LD-Reactor allows to use different components for different property types based on the config you define. So, I think it does what you are looking for, you just need to create your custom components for different entity types. It brings much more than this indeed... I thought SPARQL is a standard! Virtuoso and Fuseki should theoretically just provide different implementations of that standard!
My suggestion is to try LD-Reactor with Virtuoso to check if fulfils your needs (although it is still very beta), if yes, you can just join us to add the suitable interface for Fuseki, if not, go for your own implementation....

**Comment by killercup** [comment]
Sounds good. I'll try Virtuoso and see if I can get LD-Reactor to work. (I won't get to it until later this week, though.)

**Comment by ali1k** [comment]
good! I am also very busy this week. I will start to create a documentation for LD-Reactor next week...

**Comment by ali1k** [comment]
The documentation is almost ready.
