### ISSUE TITLE
Website needs a privacy policy

### ISSUE THREAD

**Issue by coolharsh55** [ali1k/ld-r#12]
As the information collected about an 'user' includes Name, Organisation, and Email, which constitutes as private or personal information, the website *should* have a privacy policy.

**Comment by ali1k** [comment]
Thank you for your feedback @coolharsh55 . it is just a demo and no real data is needed to be entered in the system (there is no email confirmation there). I added credentials for a test account for people who do not want to register their information in the system  (and still want to test the system): see http://demo.ld-r.org/login

**Comment by coolharsh55** [comment]
What about people who _do_ want to register? 

> it is just a demo and no real data is needed

Then why not mention this on the page? Providing a test account is well and good, but IMHO it is not a good practice to demand details that you don't need, and to not have a privacy policy.

**Comment by ali1k** [comment]
I thought 'demo' already conveys this meaning. If anyone intends to use the LD-R framework he/she needs to provide their domain-specific privacy policy information. 
Anyways, if you are a privacy policy professional and think it is really a 'must', could you please make a PR to add it to the demo?
