### ISSUE TITLE
building the app fails - unknown plugin "dev-expression"

### ISSUE THREAD

**Issue by mathib** [ali1k/ld-r#30]
## Expected Behavior
A working Linked Data app after using `npm run build`

## Actual Behavior
Following error was returned instead: <br />

```
ERROR in ./node_modules/react-leaflet/es/index.js
Module build failed: ReferenceError: Unknown plugin "dev-expression" specified in "C:\\Users\\USER-NAME\\Documents\\LD-R\\ld-r (new)\\node_modules\\react-leaflet\\.babelrc" at 0, attempted to resolve relative to "C:\\Users\\USER-NAME\\Documents\\LD-R\\ld-r (new)\\node_modules\\react-leaflet"
    at C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-loader\lib\index.js:175:20)
 @ multi react react-dom async fluxible fluxible-addons-react wicket/wicket fluxible-plugin-fetchr fluxible-router moment rc-calendar semantic-ui-react react-leaflet react-sigma lodash/collection lodash/string react-search-input classnames/bind chroma-js password-hash recharts
Child extract-text-webpack-plugin ../ld-r (new)\node_modules\extract-text-webpack-plugin\dist ../ld-r (new)\node_modules\css-loader\index.js!../ld-r (new)\node_modules\yasgui-yasqe\dist\yasqe.min.css:
       2 modules
Child extract-text-webpack-plugin ../ld-r (new)\node_modules\extract-text-webpack-plugin\dist ../ld-r (new)\node_modules\css-loader\index.js!../ld-r (new)\node_modules\rc-calendar\assets\index.css:
       2 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! linked-data-reactor@1.1.9 build: `webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the linked-data-reactor@1.1.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER-NAME\AppData\Roaming\npm-cache\_logs\2018-01-31T15_27_26_006Z-debug.log
```

## Steps to Reproduce the Problem
  1. Fresh install of LD-R
  2. Follow basic tutorial 1 (development mode works)
  3. end tutorial with building the app: `npm run build`

## Specifications
  - Version: LD-R most recent version from Github (31st of Jan 2018) = v1.1.9
  - Platform: Windows 10 (64x)
  - Subsystem: node v9.4.0 and npm v5.6.0

**Comment by mathib** [comment]
This was the debug log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'build' ]
> 2 info using npm@5.6.0
> 3 info using node@v9.4.0
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle linked-data-reactor@1.1.9~prebuild: linked-data-reactor@1.1.9
> 6 info lifecycle linked-data-reactor@1.1.9~build: linked-data-reactor@1.1.9
> 7 verbose lifecycle linked-data-reactor@1.1.9~build: unsafe-perm in lifecycle true
> 8 verbose lifecycle linked-data-reactor@1.1.9~build: PATH: C:\Users\USER-NAME\AppData\Roaming\nvm\v9.4.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\iis express\PHP\v7.1;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\Common Files\Autodesk Shared\;C:\Users\USER-NAME\Documents\stardog-4.2.3\bin;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\dotnet\;C:\Users\USER-NAME\AppData\Local\Micros;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Users\USER-NAME\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\USER-NAME\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Apache\maven\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\USER-NAME\AppData\Roaming\Composer\vendor\bin;C:\Users\USER-NAME\Documents\Toolbox\stardog-5.0.4\bin;C:\Users\USER-NAME\Documents\Toolbox\curl;C:\python27;C:\python27\Scripts;C:\python36;C:\python36\Scripts;C:\Users\USER-NAME\AppData\Roaming\nvm;C:\Program Files\nodejs;
> 9 verbose lifecycle linked-data-reactor@1.1.9~build: CWD: C:\Users\USER-NAME\Documents\LD-R\ld-r (new)
> 10 silly lifecycle linked-data-reactor@1.1.9~build: Args: [ '/d /s /c',
> 10 silly lifecycle   'webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start' ]
> 11 silly lifecycle linked-data-reactor@1.1.9~build: Returned: code: 2  signal: null
> 12 info lifecycle linked-data-reactor@1.1.9~build: Failed to exec build script
> 13 verbose stack Error: linked-data-reactor@1.1.9 build: `webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start`
> 13 verbose stack Exit status 2
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\USER-NAME\AppData\Roaming\nvm\v9.4.0\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
> 13 verbose stack     at EventEmitter.emit (events.js:160:13)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\USER-NAME\AppData\Roaming\nvm\v9.4.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:160:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:943:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> 14 verbose pkgid linked-data-reactor@1.1.9
> 15 verbose cwd C:\Users\USER-NAME\Documents\LD-R\ld-r (new)
> 16 verbose Windows_NT 10.0.16299
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> 18 verbose node v9.4.0
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 2
> 22 error linked-data-reactor@1.1.9 build: `webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start`
> 22 error Exit status 2
> 23 error Failed at the linked-data-reactor@1.1.9 build script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 2, true ]

**Comment by ali1k** [comment]
I think it is an error on Windows, could you try it with

`npm run build:windows`

and see you still get the error?

p.s. https://github.com/mui-org/material-ui/issues/2151 and https://github.com/ReactTraining/react-router/issues/2456 might be related.

**Comment by mathib** [comment]
adding 'windows' does not make a difference.

It has something to do with dependencies, I think. Maybe this can help: https://github.com/PaulLeCam/react-leaflet/issues/428

**Comment by ali1k** [comment]
indeed it is an issue with dependencies on the webpack build process. However the fact that it only occurs on Windows (everything works well on Unix), makes me suspicious that it has something to do with environmental variables which are needed to be set for production on windows. My guess is the variable`NODE_ENV=production` is not set correctly in your env and that makes Webpack build problematic.
Unfortunately I have no Windows machine to reproduce the issue. Could you please try the solutions linked above and if it works, make a PR?

**Comment by mathib** [comment]
When I did `npm install babel-plugin-dev-expression` and tried again to `npm run build`, I got the following errors:
```
ERROR in ./node_modules/react-leaflet/es/index.js
Module build failed: Error: Plugin 1 specified in "C:\\Users\\USER-NAME\\Documents\\LD-R\\ld-r (new)\\node_modules\\react-leaflet\\.babelrc" provided an invalid property of "__wrapped__"
    at Plugin.init (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:152:12)
    at C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\USER-NAME\Documents\LD-R\ld-r (new)\node_modules\babel-loader\lib\index.js:175:20)
 @ multi react react-dom async fluxible fluxible-addons-react wicket/wicket fluxible-plugin-fetchr fluxible-router moment rc-calendar semantic-ui-react react-leaflet react-sigma lodash/collection lodash/string react-search-input classnames/bind chroma-js password-hash recharts
Child extract-text-webpack-plugin ../ld-r (new)\node_modules\extract-text-webpack-plugin\dist ../ld-r (new)\node_modules\css-loader\index.js!../ld-r (new)\node_modules\yasgui-yasqe\dist\yasqe.min.css:
       2 modules
Child extract-text-webpack-plugin ../ld-r (new)\node_modules\extract-text-webpack-plugin\dist ../ld-r (new)\node_modules\css-loader\index.js!../ld-r (new)\node_modules\rc-calendar\assets\index.css:
       2 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! linked-data-reactor@1.1.9 build: `webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the linked-data-reactor@1.1.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER-NAME\AppData\Roaming\npm-cache\_logs\2018-02-01T09_42_41_233Z-debug.log
```
Same error when I used `npm run build:windows`

**Comment by ali1k** [comment]
I think we are now closer to the source of issue!
Can you do me a favor and set the env variable `NODE_ENV=production` in your windows env. restart the CMD line and then run `npm run build` ?

**Comment by mathib** [comment]
I set the env variable to `NODE_ENV=production`, but the same error appears...

**Comment by mathib** [comment]
Okay, tried to exclude node_moduels from `webpack/prod.config.js` (as mentioned in https://github.com/PaulLeCam/react-leaflet/issues/428):
initial: 
```
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules\/(?!react-sigma)/ ,
                loader: 'babel-loader',
                options: {
                    presets: [
                        ['es2015', { modules: false }]
                    ]
                }
            },
            {
```
to:
```
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: [/node_modules\/(?!react-sigma)/, /(node_modules)/] ,
                loader: 'babel-loader',
                options: {
                    presets: [
                        ['es2015', { modules: false }]
                    ]
                }
            },
            {
```

This results in the following error:
```
ERROR in vendor.bundle.js from UglifyJs
Unexpected token: operator (>) [./node_modules/react-sigma/es/tools.js:4,0][vendor.bundle.js:37702,87]
Child extract-text-webpack-plugin ../ld-r (new)\node_modules\extract-text-webpack-plugin\dist ../ld-r (new)\node_modules\css-loader\index.js!../ld-r (new)\node_modules\yasgui-yasqe\dist\yasqe.min.css:
       2 modules
Child extract-text-webpack-plugin ../ld-r (new)\node_modules\extract-text-webpack-plugin\dist ../ld-r (new)\node_modules\css-loader\index.js!../ld-r (new)\node_modules\rc-calendar\assets\index.css:
       2 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! linked-data-reactor@1.1.9 build:windows: `webpack --config ./webpack/prod.config.js && set NODE_ENV=production && npm start`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the linked-data-reactor@1.1.9 build:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER-NAME\AppData\Roaming\npm-cache\_logs\2018-02-01T10_49_10_016Z-debug.log
```

**Comment by ali1k** [comment]
I will ponder upon the issue and will come back to you as soon as I have any updates, please do the same... For now I suggest go for the docker option.

**Comment by ali1k** [comment]
I founds the origin of this error:
`exclude: /node_modules\/(?!react-sigma)/ ,`
in Windows doesn't work well because of the file path, I changed it to 
`exclude: /node_modules(?!(\/|\\)react-sigma)/ ,
which fixes the issue.
You would still need to run `nom run build:windows` because the ENV vars are set differently on windows.

**Comment by mathib** [comment]
Tested the new version, and I cannot even go in dev mode because it somehow cannot find webpack (while it did in v1.1.9 of LD-R). If I look in the local node_modules folder, I see no webpack. If I try to explicitly install webpack `npm i --save-dev webpack` locally, there is still no sign of an installed webpack in node_modules

I followed all steps from the getting started guide (installed via the bat, looked OK). Webpack was installed globally without problems (v3.10.0) on node v9.4.0

**Comment by ali1k** [comment]
I tested the issue you had reported on a windows machine and it was resolved. What you are referring to is a new issue with your webpack. Please open another ticket for that.

**Comment by najuste** [comment]
I have ran into the very similar problem on Mac:
`ERROR in ./~/react-leaflet/lib/index.js
Module build failed: ReferenceError: Unknown plugin "dev-expression" specified in "/Users/ju/Desktop/horseradish-socialnetwork/node_modules/react-leaflet/.babelrc" at 0, attempted to resolve relative to "/Users/ju/Desktop/horseradish-socialnetwork/node_modules/react-leaflet"
    at /Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/ju/Desktop/horseradish-socialnetwork/node_modules/babel-loader/lib/index.js:163:20)
 @ ./src/UsersMap.js 13:20-44
webpack: Failed to compile.`

No idea how to move forward... Installing `npm install babel-plugin-dev-expression` resulted in the same error as mathib got..
