### ISSUE TITLE
Stardog v5 and up have separate read and write endpoint

### ISSUE THREAD

**Issue by mathib** [ali1k/ld-r#32]
## Expected Behavior
I tried to configure the LD-R with a stardog database of v5.0.4 and added as in the basic example to server.js config a stardog dataset with 'http://localhost:5820/db-name/query'. After modifying the reactor.js file, I expected to be able to perform sparql updates on the properties.

## Actual Behavior
After configuring the reactor.js, I could see the option to modify/delete/add new property, but the sparql update failed on the Stardog db. The stardog endpoint could only be read, and not updated. This is probably because since v5 of stardog, there are two endpoints: one solely for reading and one solely for updating (sparql insert/delete). (https://community.stardog.com/t/query-and-update-endpoint-stardog-5/530)

## Steps to Reproduce the Problem

  1. Use a stardog endpoint (v.5 or higher)
  2. Add a stardog database in server.js, ending with /query
  3. Make the resources modifiable/deletable/addable in reactor.js
  4. Add the app and try to modify/delete/add a resource 

## Specifications

  - Version: LD-R 1.1.11
  - Platform: Windows 10

**Comment by ali1k** [comment]
I updated the Stardog sample config since they seem to have updated their endpoint URL. Can you try to use `/annex/testDB/sparql/query` as your path and see if update queries would work?

**Comment by mathib** [comment]
It works, thanks! My bad, because I overlooked those comments in the server.js config... Awesome framework :)

Do you know what the difference is when using this alternative path? I could not find anything about this in the Stardog manual. Besides that, are there options to connect to a stardog db, when it is running locally but with authentication (a user should login with a pw)? If I try it now, the web UI says: 

> There was no resource in the selected dataset! This might be due to the connection problems or because the estimated query execution time exceeds the configured limit. Please check the connection parameters of your dataset's Sparql endpoint or add resources to your dataset...

**Comment by ali1k** [comment]
good that it worked!
I don't know exactly what the difference it. It seems they have changed their APIs. At the moment, there is no support for endpoints with authentication. It is on our todo list.

**Comment by mathib** [comment]
@ali1k : I've asked to the Stardog community, how this will evolve and they said that `/annex/testDB/sparql/query` will be depreciated in next versions: https://community.stardog.com/t/stardog-sparql-endpoints/814/2

The workflow of LD-R should maybe allow to use `/query` and `/update` in the future?

**Comment by ali1k** [comment]
thanks @mathib 
I updated the SPARQL query APIs to use /query for selection queries and /update for update queries. It is still compatible with /annex one though.
