### ISSUE TITLE
SPARQL query is passed through GET for UPDATE requests

### ISSUE THREAD

**Issue by antonisloizou** [ali1k/ld-r#4]
Hi Ali,

Hope all is well :) 
I was playing around with LD-R yesterday, and noticed that if I have many properties the detail editor fails to update values. Same with numerous extensions for a new resource.

Digging around I found out that the query is passed in the URL even for POST requests, and can get truncated if it grows too large.

I replaced all instances of :
`rp.post({uri: getHTTPQuery('update', query, endpointParameters, outputFormat)}).then(function(res){`
with
`rp.post({uri: getHTTPQuery('update', query, endpointParameters, outputFormat).split('?')[0], form: {query: query, format: 'application/sparql-results+json'}}).then(function(res){`
in
`services/resource.js`

This works, but I am sure you'll have a more elegant fix in mind.

Cheers,
Antonis

**Comment by ali1k** [comment]
Hi Antonis,
I am fine, thanks :) just missed you in the group. We hoped you come by frequently ;)
thanks for bringing this issue up. I organized the code for GET and POST requests. It should work fine now both with Virtuoso and Stardog.

Cheers,
Ali
