### ISSUE TITLE
admin cannot see other registered users when using Stardog

### ISSUE THREAD

**Issue by mathib** [ali1k/ld-r#47]
When allowing other users to register to the LD-R instance, it is impossible for the admin to see new or existing applicants. The 'user list' always says: ‘0 registered users’, even if I know there is an active other user (+ checked in the DB). The console outputs the following:
`{ StatusCodeError: 400 - "{\"message\":\"Variable 'subject' in projection is not present in GROUP BY\",\"code\":\"MalformedQuery\"}"`

This might be something with the LD-R query that's not adapted for Stardog endpoints.

**Comment by ali1k** [comment]
see e.g.
https://github.com/clokman/kfir-app/blob/master/services/sparql/AdminQuery.js#L38
