### ISSUE TITLE
deploy on Heroku

### ISSUE THREAD

**Issue by mathib** [ali1k/ld-r#56]
I've noted that during deployment on Heroku, after the LD-R app is build and the changes are committed `git commit . -m 'ld-r ready'`, I get a long list of errors in build/js/main.js, almost all of them saying `strings must use singlequote quotes` . Some other errors say `expected indentation of 8 spaces but found 0`.

Managed to solve this by adding the`--no-verify` flag, to bypass the [husky checks](https://www.npmjs.com/package/husky/v/0.11.2). You might want to solve this, or add this to the [Heroku tutorial](http://ld-r.org/docs/herokuTutorial.html)

**Comment by ali1k** [comment]
thanks for the hint. I updated the tutorial but will think how to address this issue more thoroughly in future...
