### ISSUE TITLE
error while runing "npm run build "

### ISSUE THREAD

**Issue by hank123** [ali1k/ld-r#6]
C:\app\ld-r>npm run build

> linked-data-reactor@0.5.3 build C:\app\ld-r
> webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start

C:\app\ld-r\webpack\prod.config.js:1
(function (exports, require, module, __filename, __dirname) { let webpack = require('webpack');
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\app\ld-r\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\app\ld-r\node_modules\webpack\bin\webpack.js:39:40)
    at Module._compile (module.js:409:26)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! linked-data-reactor@0.5.3 build: `webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linked-data-reactor@0.5.3 build script 'webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the linked-data-reactor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config ./webpack/prod.config.js && NODE_ENV=production npm start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs linked-data-reactor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls linked-data-reactor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\app\ld-r\npm-debug.log

**Comment by ali1k** [comment]
more context needs to be provided on this issue. What OS are you using?
The new version has a major change comparing the previous one. Try the new one too...

**Comment by ali1k** [comment]
npm run build:windows on windows might work better!
