### ISSUE TITLE
Weird Behaviour

### ISSUE THREAD

**Issue by Maysk** [ali1k/ld-r#61]
Weird Behaviour in Facets:
![image](https://user-images.githubusercontent.com/7331771/62220676-d316ff00-b386-11e9-8459-badb09f7511e.png)

Piece of code in facet.js related:
![image](https://user-images.githubusercontent.com/7331771/62220535-93501780-b386-11e9-89ed-ff5d6fb4b0ac.png)

**Comment by ali1k** [comment]
Is the value of this property an integer? what happens if your turn `shortenURI` config off?

**Comment by Maysk** [comment]
You can recreate the error using the following:
  [test.zip](https://github.com/ali1k/ld-r/files/3460983/test.zip)

Inside this zip file there are the config files needed to set up the test and the sparql used to insert the triples on the dataset. I am using virtuoso triplestore.

This is what happens:
![screen-capture-_1_](https://user-images.githubusercontent.com/7331771/62367207-4ba0cb80-b4ff-11e9-9b4f-149ec50bf893.gif)
