### ISSUE TITLE
Question on setting base URI when creating a new resource

### ISSUE THREAD

**Issue by charlie42** [ali1k/ld-r#70]
When I create a new resource its URI looks like this: `http://<MY IP>:7200/c1585313868`, instead of the base URI set in GraphDB. Is it possible to configure the base URL for the new resources in ld-r?

**Comment by ali1k** [comment]
You can set the`baseResourceDomain` in configs/general.js

see more at http://ld-r.org/docs/configGeneral.html

**Comment by charlie42** [comment]
Thanks for quick reply. This didn't work, I still have new resources created with the IP based URI.

**Comment by charlie42** [comment]
I found that replacing the name of the endpoint in configs/server.js works somewhat, like this:
`'http://<BASE URL>#': {
            host: '<IP>', port: 7200, path: '/repositories/test', graphName: 'default', endpointType: 'graphdb'
 },`
but now I get an unnecessary `/` between the ID and the `#`. Any idea how to work around this?

**Comment by ali1k** [comment]
Normally the `baseResourceDomain` should do the trick. I tried to fix the issue. Can you do a `git pull` and try again.

**Comment by charlie42** [comment]
It works, thank you so much!
