### ISSUE TITLE
No users displayed in admin user list

### ISSUE THREAD

**Issue by charlie42** [ali1k/ld-r#71]
I loaded the sample users.ttl file into my triplestore (GraphDB) and also registered another user. I can log in with both users and view their profile, but when I open the Users List while signed in as admin, it says "0 Registered Users". When I click on the "0" link, it opens the N3 file with both admin and the new user. What could be the issue? Thank you.

**Comment by ali1k** [comment]
Not sure why it happens but please check the SPARQL query to retrieve the list of users. Maybe your triple store executes it differently!

**Comment by charlie42** [comment]
It was the same issue as [this](https://github.com/ali1k/ld-r/issues/47) actually! It works now, thank you.

**Comment by charlie42** [comment]
Would you like me to open a PR with this fix? I think it won't hurt to have an explicit GROUP BY.

**Comment by ali1k** [comment]
yes, would be great to add this fix! thanks @charlie42
