### ISSUE TITLE
Remove config files from gitignore

### ISSUE THREAD

**Issue by LaurensRietveld** [ali1k/ld-r#9]
The `.gitignore` file contains the config files. I get why this is here, to avoid committing credentials. But editors such as atom will hide these files, making it annoying to work with without some fiddling around.
Perhaps use a commit hook for these files instead? (e.g. using https://www.npmjs.com/package/precommit)

**Comment by ali1k** [comment]
I am not a fan of commit hooks because they get beyond the scope of project! In atom you can change the config to show the hidden files which is important to see things like .eslintrc .gitignore etc. By the way, the new version brings lot of changes esp. for dynamic configuration...
